namespace DreamFactory.Model.System.Device
{
    using DreamFactory.Model.System.User;

    /// <summary>
    /// DeviceResponse.
    /// </summary>
    public class DeviceResponse
    {
        /// <summary>
        /// Identifier of this device.
        /// </summary>
        public int? Id { get; set; }

        /// <summary>
        /// Unique ID generated by the device.
        /// </summary>
        public string Uuid { get; set; }

        /// <summary>
        /// Platform information of the device.
        /// </summary>
        public string Platform { get; set; }

        /// <summary>
        /// Version information of the device.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// Model information of the device.
        /// </summary>
        public string Model { get; set; }

        /// <summary>
        /// Extra information from the device.
        /// </summary>
        public string Extra { get; set; }

        /// <summary>
        /// Id of the User using this device.
        /// </summary>
        public int? UserId { get; set; }
        
        /// <summary>
        /// Related user by user_id.
        /// </summary>
        public RelatedUser User { get; set; }

        /// <summary>
        /// Date this device was created.
        /// </summary>
        public string CreatedDate { get; set; }

        /// <summary>
        /// Date this device was last modified.
        /// </summary>
        public string LastModifiedDate { get; set; }
    }
}
