namespace DreamFactory.Model.System.Device
{
    using DreamFactory.Model.System.User;

    /// <summary>
    /// DeviceResponse.
    /// </summary>
    public class DeviceResponse
    {
        /// <summary>
        /// Identifier of this device.
        /// </summary>
        public int? id { get; set; }

        /// <summary>
        /// Unique ID generated by the device.
        /// </summary>
        public string uuid { get; set; }

        /// <summary>
        /// Platform information of the device.
        /// </summary>
        public string platform { get; set; }

        /// <summary>
        /// Version information of the device.
        /// </summary>
        public string version { get; set; }

        /// <summary>
        /// Model information of the device.
        /// </summary>
        public string model { get; set; }

        /// <summary>
        /// Extra information from the device.
        /// </summary>
        public string extra { get; set; }

        /// <summary>
        /// Id of the User using this device.
        /// </summary>
        public int? user_id { get; set; }
        
        /// <summary>
        /// Related user by user_id.
        /// </summary>
        public RelatedUser user { get; set; }

        /// <summary>
        /// Date this device was created.
        /// </summary>
        public string created_date { get; set; }

        /// <summary>
        /// Date this device was last modified.
        /// </summary>
        public string last_modified_date { get; set; }
    }
}
