// ReSharper disable InconsistentNaming
namespace DreamFactory.Model.User
{
    /// <summary>
    /// DeviceResponse.
    /// </summary>
    public class DeviceRequest
    {
        /// <summary>
        /// Identifier of this device.
        /// </summary>
        public int? id { get; set; }

        /// <summary>
        /// Unique ID generated by the device.
        /// </summary>
        public string uuid { get; set; }

        /// <summary>
        /// Platform information of the device.
        /// </summary>
        public string platform { get; set; }

        /// <summary>
        /// Version information of the device.
        /// </summary>
        public string version { get; set; }

        /// <summary>
        /// Model information of the device.
        /// </summary>
        public string model { get; set; }

        /// <summary>
        /// Extra information from the device.
        /// </summary>
        public string extra { get; set; }
    }
}
