namespace DreamFactory.Model.User
{
    /// <summary>
    /// DeviceResponse.
    /// </summary>
    public class DeviceRequest
    {
        /// <summary>
        /// Identifier of this device.
        /// </summary>
        public int? Id { get; set; }

        /// <summary>
        /// Unique ID generated by the device.
        /// </summary>
        public string Uuid { get; set; }

        /// <summary>
        /// Platform information of the device.
        /// </summary>
        public string Platform { get; set; }

        /// <summary>
        /// Version information of the device.
        /// </summary>
        public string Version { get; set; }

        /// <summary>
        /// Model information of the device.
        /// </summary>
        public string Model { get; set; }

        /// <summary>
        /// Extra information from the device.
        /// </summary>
        public string Extra { get; set; }
    }
}
